### PR TITLE
Add install functions and prepare for distribution

### PR DESCRIPTION
**Pull request by zerebos**

### CODE REVIEW

**Review by zolee01 — COMMENTED** [review]
Tru

**Comment by NeverLiez** [comment]
https://apps.apple.com/app/github/id1477376905?ls=1

**Review by NeverLiez — COMMENTED** [review]
Very good

**Review by bakaryponcho — COMMENTED** [review]
Merci

**Review by 641210 — COMMENTED** [review]
**image**

**Pull request merged**
