### PR TITLE
Add asar file selection dialog when the download fails

### PR DESCRIPTION
**Pull request by QbDesu**
from a conversation about the topic on the Discord server

> A:  Why would you ever build an asar and need to use the installer for it?

> Qb: No some people just can't figure out why their download fails, even if told to disable their antivirus/firewall. Let's be frank most of them probably just don't know how to do it but it's not our job to figure out how to turn it of for them. So there is a dialog that only shows when it fails that has both a message telling you to try turning it off, a button for retrying the download, and a button that opens a file picker for selection of a local `betterdiscord.asar` file.

> A: Unfortunately if people can't turn their av off I doubt they can download and select an asar file
> A: They'll just try run the file

> Qb: well when providing support you can link them to the asar file and tell them to click the Browse button on the dialog that pops up in the installer. And even if do agree some people are just stupid that doesn't stop them from whining and asking what to do when they can't figure it out.
> Qb: So it's mostly intended so people giving support have something to tell the people so they'll be quiet.

This is mostly a draft to get this working, it shows a native dialog with a small info text telling people to try turning off their Antivirus/Firewall when the download fails. It has 3 buttons "Retry", "Browse", and "Cancel".

I'm not quite happy with how the code looks, the message may need some rewording; maybe allowing the user to specify an asar file some other way and not when the download fails would be better. Lots of things to consider on this one, happy to hear any feedback.

### CODE REVIEW

**Comment by tropicaaal** [comment]
This will be considered, but seeing as how some of the userbase fail to use the GUI oriented part of the installer, it would probably be less confusing to the average person to just give an error message.

**Comment by QbDesu** [comment]
The most important part to me with this PR is to have an option provide a local asar file, that is out of the way of the average user as to not any unnecessary confusion. The way I currently show it will probably confuse some users that really should just disable their firewall/antivirus temporarily. But a user that is instructed by someone from support should be able to do it manually when the the installer fails to download the asar file. (I've asked some people whose downloads were blocked to manually download the file and it wasn't blocked there) This could also look differently. Like maybe repair has options to choose from like the BBD installer had, or an maybe another 'Advanced' action although that would usually also only confuse people. 

Another important consideration this PR includes is actually giving advise on common fixes for when things fail in the installer.

**Comment by zerebos** [comment]
> Another important consideration this PR includes is actually giving advise on common fixes for when things fail in the installer.

While this in principle is good, the purpose of the PR is less so. I tend to agree with Tropical here.

**Comment by QbDesu** [comment]
I think I'll put this one to rest.
While it was kinda helpful as a quite user-unfriendly temporary fix for the redirect issue that's not something that happens usually and I would not have done it this way if I didn't have it ready this way already.
However, this does not mean I'll drop it entirely. On the support server it has been used to provide support for users that didn't manage to disable their anti-virus software numerous times since it I posted it on the server as a test version, and I still think it's quite helpful for that.
But I also realized you don't want to show this option to an user that isn't being instructed by someone else. So I think the way I'll do this is to still make a version that has these changes included but only share it with people who need it over the support server. (Although of course me just sharing a binary around isn't ideal either. while I'm glad people trusted me enough it''s still not really great in principle)

As far as giving more helpful error messages is concerned we probably want to link to a troubleshooting guide in the planned docs on the betterdiscord website, until then that's that.

**Pull request closed without merging**
