### PR TITLE
Remove requirement to agree to the MIT license since that is not required

### PR DESCRIPTION
**Pull request by j-f1**
This makes it quicker to get started using BetterDiscord by removing two clicks and some thinking. Instead, I link to [BetterDiscord’s license](https://github.com/rauenzi/BetterDiscordApp/blob/main/LICENSE) in the footer.

Screenshot_2021-05-14 14 01 54

### CODE REVIEW

**Comment by tropicaaal** [comment]
@rauenzi thoughts on this?

**Comment by j-f1** [comment]
alternative that I’m happy to push, to make it more clear:

Screenshot_2021-05-23 18 00 40

**Comment by dav1312** [comment]
> alternative that I’m happy to push, to make it more clear:
> 
> Screenshot_2021-05-23 18 00 40

If you are going to add a [link to the license](https://github.com/BetterDiscord/Installer/pull/130/files#diff-0b9d7f4d729e7fcc63acf64e8250d042ef72336910fd6de51ac2ad184e762684R5) when clicking the button it should be to the **installer license** since **Betterdiscord** itself **is not MIT Licensed**

**Comment by j-f1** [comment]
updated to clarify that the link is to the BetterDiscord license since that is relevant because it has restrictions.

**Comment by zerebos** [comment]
I don't believe removing this is a good idea, it is important for this final line of the license to be there and to be agreed to:

        THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
        AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
        LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
        OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
        SOFTWARE.

**Pull request closed without merging**
