### PR TITLE
Add a checkmark to the selected discord versions for clarity

### PR DESCRIPTION
**Pull request by j-f1**
When I first used the installer, I was a little confused by this screen. IMO the checkmarks make it more explicit which versions are selected.

Screenshot_2021-05-14 13 54 05

### CODE REVIEW

**Comment by tropicaaal** [comment]
I would probably include these before the browse buttons. These can be implimented in the next update.

**Comment by j-f1** [comment]
Updated!

Screenshot_2021-05-23 17 57 27

**Comment by dav1312** [comment]
When you actually select the Discord version it's very clear that it's selected.
The problem is that some people don't know that you have to select one of them. Probably because in the previous step, the install option is selected by default and users expect the same behaviour.

A warning should appear when attempting to click or actually clicking the "Install" button without any Discord version selected.
And maybe change "Choose" to "Select" to make it even more clear.

**Comment by QbDesu** [comment]
I'd say if there is only one version of Discord detected it should always automatically select that one.
(If there is more than one version of discord detected and stable is one of them maybe select stable by default)
The install button should have a tooltip saying something along the lines of `Please select a Discord version to install BetterDiscord to`
And lastly chosing a location using the `Browse` button should automatically select the version that you were browsing for.

In my opinion this PR misses the probem by adding a checkmark but no checkbox. The problem is not so much that people don't realize something is selected when it is; Rather people don't realize the the whole thing is a big button, so they only try clicking browse and not the button itself. But adding a checkmark on top of the proposals above would still be good for added clarity.

**Pull request closed without merging**
