### PR TITLE
updated to include discord development

### PR DESCRIPTION
**Pull request by moongazer07**

### CODE REVIEW

**Comment by maenDisease** [comment]
https://github.com/BetterDiscord/Installer/issues/87#issuecomment-877503627

**Comment by moongazer07** [comment]
> [#87 (comment)](https://github.com/BetterDiscord/Installer/issues/87#issuecomment-877503627)

also trying to build but build keeps failing so far only linux builds

**Comment by moongazer07** [comment]
⨯ Env WIN_CSC_LINK is not correct, cannot resolve: D:\a\Installer\Installer not a file

**Comment by zerebos** [comment]
Development is a dead client. This also seems to remove the Mac build from our CI for some reason...

**Comment by moongazer07** [comment]
> Development is a dead client. This also seems to remove the Mac build from our CI for some reason...

 was trying to see if mac build removal temp would allow windows to build but it did not work windows still failed

**Comment by moongazer07** [comment]
i have restored the original cli

**Comment by moongazer07** [comment]
it built just fine without code sign

**Comment by moongazer07** [comment]
it compiled for all releases but failed at [Push Version Bump](https://github.com/moongazer07/Installer/actions/runs/5051772940/jobs/9064014818#step:2:13)
Input required and not supplied: token

**Pull request closed without merging**
