### PR TITLE
Add compatible with Discord Portable (portapps)

### PR DESCRIPTION
**Pull request by mokocup**
I see alot of people asking for this in BBD Server so i made it.
The problem why Installer not work on portapps's Discord become it unpack the app.asar to app folder and use it own folder for user data

Tested on latest portapps's Discord PTB 1.0.1008-16

**Status**

* Install : Working , run only when platform is window (win32)
* Uninstall : Working but lossy , leaving app.asar instead of app folder like original
* Repair : Not working , unable to delete modules folder

### CODE REVIEW

**Comment by mokocup** [comment]
Tested on 
* Window 10 EE with portapps's Discord PTB 1.0.1008-16 and latest Discord PTB 1.0.1010 

### **Installer Status**
* Install : Working , portable only run when platform is window (win32)
* Uninstall : Working , leaving app.asar instead of app folder like original
* Repair : Working

### **Injector and BBD Status**
Am currently using BBD with Portapp's Discord now and got no crash so far with some themes and plugins , all data go to Portapp's Discord Data folder.
So as long as BBD use getPath , it will work fine

**Comment by zerebos** [comment]
I'm not sure if this is something we intend to support, especially as there may be a change to how the injection is performed soon, but I will consider it nonetheless.

p.s. BBD is long since dead, not sure why you still use that initialism.

**Comment by mokocup** [comment]
Thanks for consider about Portapp's Discord

> especially as there may be a change to how the injection is performed soon

I will try make it work anyway since my work enviroment require use Portapp's DIscord and i want my waifu themes , not my first time make BD work on Portapp's Discord

> p.s. BBD is long since dead, not sure why you still use that initialism.

Yes , its longggg way back . Just recent my work partner keep complaint about BD with Portapp so i comeback to make it work "again"

**Comment by pozhiloy-enotik** [comment]
thank you

**Review by pozhiloy-enotik — APPROVED** [review]

**Comment by zerebos** [comment]
We are not moving forward with this at this time

**Pull request closed without merging**
